name: Build EuroScope Plugin

on: 
  push:
    branches: [ "main", "2026-04-25-SSL-Update" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install MFC and ATL
        uses: ammaraskar/setup-cpp@master
        with:
          visual-studio-version: '2022'
          components: 'Microsoft.VisualStudio.Component.VC.ATLMFC;Microsoft.VisualStudio.Component.VC.v142.MFC;Microsoft.VisualStudio.Component.VC.v142.ATL'

      - name: Install Dependencies via vcpkg
        run: |
          vcpkg integrate install
          vcpkg install curl:x86-windows nlohmann-json:x86-windows

      - name: Build Solution
        run: |
          msbuild VATCANSitu.sln /p:Configuration=Release /p:Platform=x86 /p:VcpkgEnableManifest=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VATCAN-Slots-Plugin
          path: |
            Release/*.dll